const data = [
  {
    tipo: "resultado",
    data: "2023-07-26",
    medico: "Dr. Luis Fernando",
    procedimento: "Espirometria",
    empresa: "Neuromaster",
    aguardando: true,
  },
  {
    tipo: "resultado",
    data: "2023-07-26",
    medico: "Dr. Luis Fernando",
    procedimento: "Espirometria",
    empresa: "Neuromaster",
    aguardando: true,
  },
  {
    tipo: "resultado",
    data: "2023-07-24",
    medico: "Dr. João Marcelo",
    procedimento: "Holter",
    empresa: "Neuromaster",
    aguardando: false,
  },
  {
    tipo: "resultado",
    data: "2023-07-24",
    medico: "Dr. João Marcelo",
    procedimento: "Holter",
    empresa: "Neuromaster",
    aguardando: false,
  },
  {
    tipo: "resultado",
    data: "2023-07-24",
    medico: "Dr. João Marcelo",
    procedimento: "Holter",
    empresa: "Neuromaster",
    aguardando: false,
  },
  {
    tipo: "exame",
    data: "2023-07-23",
    medico: "Dr. João Marcelo",
    procedimento: "",
    empresa: "Neuromaster",
  },
  {
    tipo: "resultado",
    data: "2023-07-10",
    medico: "Dr. Wanderson",
    procedimento: "Doppler",
    empresa: "Clinica de Veias",
    aguardando: false,
  },
  {
    tipo: "atestado",
    data: "2023-07-26",
    medico: "Dr. Luis Fernando",
    procedimento: "",
    empresa: "Neuromaster",
  },
  {
    tipo: "receita",
    data: "2023-07-26",
    medico: "Dr. Luis Fernando",
    procedimento: "",
    empresa: "Clinica de Veias",
  },
  {
    tipo: "relatorio",
    data: "2023-05-30",
    medico: "Dr. André Stein",
    procedimento: "",
    empresa: "Neuromaster",
  },
];

export default data;
